### ISSUE TITLE
Best settings for H265

### ISSUE THREAD

**Issue by MarkGhanz** [fzwoch/obs-vaapi#10] opened 2023-02-26 22:32 UTC
Is there a better setting for h265? The default setting can easily overload the encoder and output a video of bitrate several hundred mbps if setting the bitrate to 0 (auto calculate). 
But H265(legacy) and the h265 option from obs-gstreamer plugin works fine. Can it be a regression of gstreamer?

Graphics Card: RX 7900 XT
Mesa version: 23.0.0
gstreamer vaapi version: 1.22.0
OS: Arch Linux
Kernel Version: 6.2.1
OBS Version: 29.0.2

**Comment by fzwoch** [comment] 2023-02-27 08:09
There should have been a log with settings attached for such a report.

Defaults with neither version are tuned for OBS. You will need to know about these settings and set them to your use case. As they are two different encoders their settings may be quite different. 1080p60 seemed fine to me. Everything else you probably would have to report to GStreamer.

**Comment by fzwoch** [comment] 2023-03-01 10:14
For my own tracking:
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1991

Thanks for taking it upstream!

**Comment by Atemu** [comment] 2023-03-28 03:38
@Big-FG thanks for the investigation.

Note that the entire point of CQP is to have a variable *bitrate* but relatively constant *quality* given the content.  
If you had a video with a few seconds of high movement and then a few seconds of a static image, those sections would require wildly different bitrates. With CBR, they'd get the same bitrate however; making the high-movement scene look pretty bad and the static image not much better.

CQP is for recordings where the exact bitrate at any given time doesn't matter much (but average bitrate does to a degree) and CBR for streaming where both current and average need to be relatively stable.

**Comment by Big-FG** [comment] 2023-03-28 07:02
> @Big-FG thanks for the investigation.
> 
> Note that the entire point of CQP is to have a variable _bitrate_ but relatively constant _quality_ given the content. If you had a video with a few seconds of high movement and then a few seconds of a static image, those sections would require wildly different bitrates. With CBR, they'd get the same bitrate however; making the high-movement scene look pretty bad and the static image not much better.
> 
> CQP is for recordings where the exact bitrate at any given time doesn't matter much (but average bitrate does to a degree) and CBR for streaming where both current and average need to be relatively stable.

Im aware, but what i mean by "go pretty nuts" is itll suddenly shoot to hundreds of megabits per second and overload the encoder in situations it really shouldnt be. The issue is acknowledged in the post just before mine and ive even experienced it to a lesser degree at lower resolutions.

The encoder simply behaves better with CBR at the moment with H.265 especially if youre recording 4k. I was recording 720p 60fps at CQP 24 and it was spiking in excess of 100mb/s which I dont have on happen on AMF, the Old Encoder, or the old OBS patch for HEVC.

**Comment by Atemu** [comment] 2023-03-28 08:14
Interesting. Not sure that has anything to do with this add-on as it simply uses/configures the gstreamer VAAPI encoder whose responsibility it is to implement things like CQP.

As a workaround, I believe you can set a reasonable bitrate limit.

**Comment by fzwoch** [comment] 2024-03-05 07:35
Closing this. No idea what the exact status is, but if there is still something wrong it sounds like an upstream issue.

**Closed by fzwoch** 2024-03-05 07:35 UTC
